0 0 * * * ~/aws/automation/reboot/ad/reboot-ad-00.sh
0 1 * * * ~/aws/automation/reboot/ad/reboot-ad-01.sh
0 2 * * * ~/aws/automation/reboot/ad/reboot-ad-02.sh
0 3 * * * ~/aws/automation/reboot/ad/reboot-ad-03.sh
0 4 * * * ~/aws/automation/reboot/ad/reboot-ad-04.sh
0 5 * * * ~/aws/automation/reboot/ad/reboot-ad-05.sh
0 6 * * * ~/aws/automation/reboot/ad/reboot-ad-06.sh
0 7 * * * ~/aws/automation/reboot/ad/reboot-ad-07.sh
0 8 * * * ~/aws/automation/reboot/ad/reboot-ad-08.sh
0 9 * * * ~/aws/automation/reboot/ad/reboot-ad-09.sh
0 10 * * * ~/aws/automation/reboot/ad/reboot-ad-10.sh
0 11 * * * ~/aws/automation/reboot/ad/reboot-ad-11.sh
0 12 * * * ~/aws/automation/reboot/ad/reboot-ad-12.sh
0 13 * * * ~/aws/automation/reboot/ad/reboot-ad-13.sh
0 14 * * * ~/aws/automation/reboot/ad/reboot-ad-14.sh
0 15 * * * ~/aws/automation/reboot/ad/reboot-ad-15.sh
0 16 * * * ~/aws/automation/reboot/ad/reboot-ad-16.sh
0 17 * * * ~/aws/automation/reboot/ad/reboot-ad-17.sh
0 18 * * * ~/aws/automation/reboot/ad/reboot-ad-18.sh
0 19 * * * ~/aws/automation/reboot/ad/reboot-ad-19.sh
0 20 * * * ~/aws/automation/reboot/ad/reboot-ad-20.sh
0 21 * * * ~/aws/automation/reboot/ad/reboot-ad-21.sh
0 22 * * * ~/aws/automation/reboot/ad/reboot-ad-22.sh
0 23 * * * ~/aws/automation/reboot/ad/reboot-ad-23.sh
